### ISSUE TITLE
Add distance from alert location [feature request]

### ISSUE THREAD

**Issue by potat0man** [amitfin/oref_alert#121]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/amitfin/oref_alert/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Alert showing unfamiliar location

### Describe the solution you'd like

Showing distance from alert location to phone location or home zone

### Describe alternatives you've considered

templates

### Additional context

possible to show distance from geo_location entity with formula:
{{ distance('zone.home', 'geo_location.oref_alert_location_')|round }} km

**Comment by amitfin** [comment]
Please elaborate. I'm not sure I understand the details of the ask.
BTW, `geo_location` entities includes the distance to `zone.home` - see [here](https://github.com/amitfin/oref_alert/blob/9eb5afbfbcf25ab2acd21f7c40a0f12c2c6d7f3f/custom_components/oref_alert/geo_location.py#L82).

**Comment by potat0man** [comment]
Sorry for not explaining better,
I think would be useful to show distance in notifications from alert location for example instead of:
התראות פיקוד העורף: אל-עראמשה
which is not helpful if you don't know where it is, wolud be more helpful:
התראות פיקוד העורף: אל-עראמשה [מרחק 123קמ]
created entities shows distance but I did not succeed showing it in notifications

**Comment by potat0man** [comment]
got it semi working with flex-table-card:
<img width="553" alt="121212" src="https://github.com/user-attachments/assets/b262acaa-75ce-4900-aad3-a362dc573510">
```
type: custom:auto-entities
sort:
  method: state
  numeric: true
filter:
  include:
    - entity_id: /geo_location.oref_alert_location_*/
card:
  type: custom:flex-table-card
  clickable: true
  columns:
    - data: date
      name: Date
      modify: x.split('T')[0]
    - data: date
      name: Time
      modify: x.split('T')[1].split('+')[0]
    - data: state
      name: Distance
      modify: x +" km"
    - data: friendly_name
      name: Location
```
and markdown message replacement:
<img width="550" alt="232323" src="https://github.com/user-attachments/assets/0ac9684c-8acb-458d-8d7c-3abe0b653078">
```
type: custom:flex-table-card
clickable: true
entities:
  include: binary_sensor.oref_alert_all_areas
columns:
  - data: country_active_alerts
    name: Date
    modify: x.alertDate.split(' ')[0]
  - data: country_active_alerts
    name: Time
    modify: x.alertDate.split(' ')[1]
  - data: country_active_alerts
    modify: x.title
    name: Category
  - data: country_active_alerts
    modify: x.data
    name: Location
  - data: country_active_alerts
    name: icon
    modify: |-
      if (x.category==1)
        '<font color="red"><ha-icon icon="mdi:rocket-launch"></ha-icon></font>'
      else if (x.category==2)
        '<font color="red"><ha-icon icon="mdi:airplane-alert"></ha-icon></font>'
      else if (x.category==3)
        '<font color="red"><ha-icon icon="mdi:chemical-weapon"></ha-icon></font>'
      else if (x.category==4)
        '<font color="red"><ha-icon icon="mdi:alert"></ha-icon></font>'
      else if (x.category==5)
        '<font color="red"><ha-icon icon="mdi:firework"></ha-icon></font>'
      else if (x.category==6)
        '<font color="red"><ha-icon icon="mdi:firework"></ha-icon></font>'
      else if (x.category==7)
        '<font color="red"><ha-icon icon="mdi:earth"></ha-icon></font>'
      else if (x.category==8)
        '<font color="red"><ha-icon icon="mdi:earth"></ha-icon></font>'
      else if (x.category==9)
        '<font color="red"><ha-icon icon="mdi:nuke"></ha-icon></font>'
      else if (x.category==10)
        '<font color="red"><ha-icon icon="mdi:shield-home"></ha-icon></font>'
      else if (x.category==11)
        '<font color="red"><ha-icon icon="mdi:home-flood"></ha-icon></font>'
      else if (x.category==12)
        '<font color="red"><ha-icon icon="mdi:biohazard"></ha-icon></font>'
      else if (x.category==13)
        '<font color="red"><ha-icon icon="mdi:update"></ha-icon></font>'
      else if (x.category==14)
        '<font color="red"><ha-icon icon="mdi:flash-alert"></ha-icon></font>'
      else if (x.category==15)
        '<font color="red"><ha-icon icon="mdi:alert-circle-check"></ha-icon></font>'
      else if (x.category==16)
        '<font color="red"><ha-icon icon="mdi:alert-circle-check"></ha-icon></font>'
      else if (x.category==17)
        '<font color="red"><ha-icon icon="mdi:alert-circle-check"></ha-icon></font>'
      else if (x.category==18)
        '<font color="red"><ha-icon icon="mdi:alert-circle-check"></ha-icon></font>'
      else if (x.category==19)
        '<font color="red"><ha-icon icon="mdi:alert-circle-check"></ha-icon></font>'
      else if (x.category==20)
        '<font color="red"><ha-icon icon="mdi:alert-circle-check"></ha-icon></font>'
      else if (x.category==21)
        '<font color="red"><ha-icon icon="mdi:alert-circle-check"></ha-icon></font>'
      else if (x.category==22)
        '<font color="red"><ha-icon icon="mdi:alert-circle-check"></ha-icon></font>'
```

this way the first table can't show category and icon and second table can't show distance so best solution would be adding distance attribute to binary_sensor.oref_alert and  binary_sensor.oref_alert_all_areas

**Comment by amitfin** [comment]
[v2.14.0](https://github.com/amitfin/oref_alert/releases/tag/v2.14.0) adds additional attributes to `geo_location` entities, so it's possible to get all data from there.
The documentation includes a card example with the distance: https://github.com/amitfin/oref_alert?tab=readme-ov-file#presenting-active-alerts-in-israel

@potat0man , please comment if it solves the scenario.

**Comment by potat0man** [comment]
Yes it is exactly what I meant
Thank you it's great.

**Comment by potat0man** [comment]
solved

**Comment by potat0man** [comment]
Thought it solved but was mistaken, distanse can be shown only in lovelace card but not in notifications.
I'll try making template linking 'binary_sensor' 'data' attribute and 'geo_location' 'friendly_name' attribute maybe this way it will work

**Comment by yalmog99** [comment]
Thanks for this update.
2 questions:
1. Is it possible to presenting Active Alerts in Israel both with the distance and with the type (missile / aircraft etc) ? the current example in the documentation only include the distance and not the type (it was excluded).
2. Is it possible to create an automation trigger (for example to send notification) where the distance is less the 30 KM from Home ?

**Comment by potat0man** [comment]
@amitfin thank you this is exactly what needed, this request is closed
@yalmog99 your first question can be written in title like this:
```
  - action: notify.mobile_app_iphone
    data:
      title: "{{ state_attr(trigger.event.data.entity_id, 'title') }}"
      message: >-
        {{ state_attr(trigger.event.data.entity_id, 'friendly_name') }} ({{
        states(trigger.event.data.entity_id) | int }} ק״מ)
```

my next goals with this integration:
- add icon in notifications for category
- replace letters with icons for category on maps

if I'll make it I'll update

**Comment by amitfin** [comment]
@yalmog99 

> Is it possible to create an automation trigger (for example to send notification) where the distance is less the 30 KM from Home ?

```
- id: "1728226820317"
  alias: Oref Alert Notification With Distance
  triggers:
    - trigger: event
      event_type: entity_registry_updated
      event_data:
        action: create
  actions:
    - condition: "{{ trigger.event.data.entity_id.startswith('geo_location.oref_alert_location') }}"
    - condition: "{{ states(trigger.event.data.entity_id) | int < 30 }}"
    - action: notify.mobile_app_amits_iphone2
      data:
        title: התרעות פיקוד העורף
        message: "{{ state_attr(trigger.event.data.entity_id, 'friendly_name') }} ({{ states(trigger.event.data.entity_id) | int }} ק״מ)"
```
