### ISSUE TITLE
Template variable warning

### ISSUE THREAD

**Issue by Ofir-P** [amitfin/oref_alert#187]
## System Information

version | core-2025.3.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.2
os_name | Linux
os_version | 6.12.18-haos
arch | x86_64
timezone | Asia/Jerusalem
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4994
Installed Version | 2.0.5
Stage | running
Available Repositories | 1624
Downloaded Repositories | 38

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 21

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | January 10, 2026 at 2:00 AM
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
cloud_ice_servers_enabled | true
remote_server | eu-central-1-15.ui.nabu.casa
certificate_status | ready
instance_id | xxxxx
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 15.0
-- | --
update_channel | stable
supervisor_version | supervisor-2025.03.3
agent_version | 1.7.2
docker_version | 28.0.1
disk_total | 30.8 GB
disk_used | 15.8 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Terminal & SSH (9.16.0), Studio Code Server (5.18.3), Home Assistant Google Drive Backup (0.112.1), Mosquitto broker (6.5.0), Zigbee2MQTT (2.1.3-1), eufy-security-ws (1.9.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 28
views | 15
mode | yaml

</details>

<details><summary>Network Configuration</summary>

adapters | lo (disabled), enp0s18 (enabled, default, auto), docker0 (disabled), hassio (disabled), veth5d1edf7 (disabled), veth8f24a3a (disabled), veth32bd611 (disabled), veth806e285 (disabled), veth24e3132 (disabled), vethb931688 (disabled), veth0c0ba7c (disabled), vethf5f13f9 (disabled), veth46bfdfd (disabled), veth0797ce2 (disabled), veth1df6c7b (disabled), veth12ccd31 (disabled)

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | March 19, 2025 at 5:00 PM
-- | --
current_recorder_run | March 30, 2025 at 10:26 AM
estimated_db_size | 410.54 MiB
database_engine | sqlite
database_version | 3.48.0

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 1.0.15
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 6

</details>

### Checklist

- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of any [previous issues](https://github.com/amitfin/oref_alert/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hi Amit!

Recently, I have received this warning on my `Logs` whenever the automation is firing.

`Template variable warning: 'alerts' is undefined when rendering 'אזעקות ב: {{ alerts | join(' | ') }}'`

```
alias: Red Alert notifications to LG Living Room TV
description: ""
triggers:
  - entity_id: binary_sensor.oref_alert_all_areas
    attribute: country_active_alerts
    trigger: state
conditions: []
actions:
  - variables:
      current: >-
        {{ state_attr('binary_sensor.oref_alert_all_areas',
        'country_active_alerts') | map(attribute='data') | list }}
      previous: >-
        {{ trigger.from_state.attributes.country_active_alerts |
        map(attribute='data') | list }}
      alerts: "{{ current | reject('in', previous) | unique | sort | list }}"
  - condition: template
    value_template: "{{ alerts | length > 0 }}"
  - if:
      - condition: state
        entity_id: input_select.living_room_tv_status
        state: "On"
    then:
      - action: notify.living_room_lg_webos_smart_tv
        metadata: {}
        data:
          message: "אזעקות ב: {{ alerts | join(' | ') }}"
  - action: script.send_red_alert_notification_to_bedroom_tv
    metadata: {}
    data: {}
mode: single
```

### Reproduction steps

1. Wait for Hutis / Hamas to fire missiles on Israel.
2. Automation will trigger
3. Warning will show on Logs

..

### Debug logs

```text
N/A
```

**Comment by amitfin** [comment]
Please post screenshots or the content of the automation traces (the ... menu has traces option). 
BTW, you can also try to reproduce the warning with synthetic alert (see documentation if you are not familiar with it).

**Comment by Ofir-P** [comment]
> Please post screenshots or the content of the automation traces (the ... menu has traces option). BTW, you can also try to reproduce the warning with synthetic alert (see documentation if you are not familiar with it).

It only happens on large area missile alerts (I think).
We must wait for that because the warning trace one is already gone.

**Comment by amitfin** [comment]
I vaguely remember similar issue in the past. Here is how my automation rule looks like:

  actions:
    - condition: "{{ 'country_active_alerts' in trigger.to_state.attributes }}"
    - condition: "{{ 'country_active_alerts' in trigger.from_state.attributes }}"
    - variables:
        current: "{{ trigger.to_state.attributes.country_active_alerts | map(attribute='data') | list }}"
        previous: "{{ trigger.from_state.attributes.country_active_alerts | map(attribute='data') | list }}"
        alerts: "{{ current | reject('in', previous) | unique | sort | list }}"
    - condition: "{{ alerts | length > 0 }}"

You can give it a try.

**Comment by Ofir-P** [comment]
> I vaguely remember similar issue in the past. Here is how my automation rule looks like:
> 
> actions: - condition: "{{ 'country_active_alerts' in trigger.to_state.attributes }}" - condition: "{{ 'country_active_alerts' in trigger.from_state.attributes }}" - variables: current: "{{ trigger.to_state.attributes.country_active_alerts | map(attribute='data') | list }}" previous: "{{ trigger.from_state.attributes.country_active_alerts | map(attribute='data') | list }}" alerts: "{{ current | reject('in', previous) | unique | sort | list }}" - condition: "{{ alerts | length > 0 }}"
> 
> You can give it a try.

Will give it a try, so the actual notify. action will remain the same? 
`message: "התרעות פיקוד העורף: {{ alerts | join(' | ') }}"`

**Comment by Ofir-P** [comment]
Still getting the warning, after this morning alerts.

![Image](https://github.com/user-attachments/assets/327b342e-b02c-4ec2-b67e-d47cc61ed344)

![Image](https://github.com/user-attachments/assets/a0f7d1d2-e185-4fc8-82aa-0dabd80364a4)


[trace automation.oref_alert_country_notifications 2025-04-01T05_36_32.057308+00_00.json](https://github.com/user-attachments/files/19545496/trace.automation.oref_alert_country_notifications.2025-04-01T05_36_32.057308%2B00_00.json)

Automation YAML:
```
alias: Oref Alert Country Notifications
description: ""
triggers:
  - entity_id: binary_sensor.oref_alert
    attribute: country_active_alerts
    trigger: state
actions:
  - condition: "{{ 'country_active_alerts' in trigger.to_state.attributes }}"
  - condition: "{{ 'country_active_alerts' in trigger.from_state.attributes }}"
  - variables:
      current: >-
        {{ trigger.to_state.attributes.country_active_alerts |
        map(attribute='data') | list }}
      previous: >-
        {{ trigger.from_state.attributes.country_active_alerts |
        map(attribute='data') | list }}
      alerts: "{{ current | reject('in', previous) | unique | sort | list }}"
  - condition: "{{ alerts | length > 0 }}"
  - data:
      message: "התרעות פיקוד העורף: {{ alerts | join(' | ') }}"
    action: notify.mobile_app_ofir_honor_magic_5_pro
  - if:
      - condition: state
        entity_id: sensor.ofir_honor_magic_5_pro_wifi_connection_2
        state: AutoKit8D
    then:
      - action: notify.whatsapp
        data:
          message: " {{ alerts | join(' | ') }}"
mode: queued
max: 100
max_exceeded: silent
```

Thanks for your help!

**Comment by amitfin** [comment]
Did you add the first 2 conditions to verify the existence of the attributes?

**Comment by Ofir-P** [comment]
> Did you add the first 2 conditions to verify the existence of the attributes?

I did.
```

alias: Red Alert notifications to LG Living Room TV
description: ""
triggers:
  - entity_id: binary_sensor.oref_alert_all_areas
    attribute: country_active_alerts
    trigger: state
conditions: []
actions:
  - condition: "{{ 'country_active_alerts' in trigger.to_state.attributes }}"
  - condition: "{{ 'country_active_alerts' in trigger.from_state.attributes }}"
  - variables:
      current: >-
        {{ trigger.to_state.attributes.country_active_alerts |
        map(attribute='data') | list }}
      previous: >-
        {{ trigger.from_state.attributes.country_active_alerts |
        map(attribute='data') | list }}
      alerts: "{{ current | reject('in', previous) | unique | sort | list }}"
  - condition: "{{ alerts | length > 0 }}"
  - if:
      - condition: state
        entity_id: input_select.living_room_tv_status
        state: "On"
    then:
      - action: notify.living_room_lg_webos_smart_tv
        metadata: {}
        data:
          message: "אזעקות ב: {{ alerts | join(' | ') }}"
  - action: script.send_red_alert_notification_to_bedroom_tv
    metadata: {}
    data: {}
mode: single

```

Same warning appears.
