### ISSUE TITLE
(Synthetic) update causes automation to fire twice

### ISSUE THREAD

**Issue by jemaltz** [amitfin/oref_alert#222]
### System Health details

Honestly, I couldn't even find this - will check again if necessary. 

### Checklist

- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of any [previous issues](https://github.com/amitfin/oref_alert/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The new update attribute does not change the state of the Oref Alert sensor. As such, an automation waiting for a state change to the `oref_alert` entity with the attribute of `selected_areas_update` (as described in the README) will be fired twice: once when the trigger is set, and then when the trigger is unset.

### Reproduction steps

This can be reproduced with a synthetic update e.g. for ten seconds: The automation will fire when the synthetic update is issued, and again after ten seconds (when the update is "over")

It is not clear at this time how this will be handled in the event of a real (non-synthetic) update.

### Debug logs

```text
will provide if necessary
```

**Comment by amitfin** [comment]
I'm working on adding HA's events for updates.

Meanwhile, can you elaborate on the problem?
The [README example](https://github.com/amitfin/oref_alert?tab=readme-ov-file#updates) has the following trigger:
```
trigger: state
entity_id: binary_sensor.oref_alert
attribute: selected_areas_updates
```
This trigger is fired ONLY when the attribute changes. A state change with no attribute change doesn't trigger it. 
See more [here](https://www.home-assistant.io/docs/automation/trigger/#triggering-on-attribute-changes):

![Image](https://github.com/user-attachments/assets/30ed64b7-fb4a-40a4-8aaf-08aca3fac024)

**Comment by amitfin** [comment]
May you are missing this part?

![Image](https://github.com/user-attachments/assets/3493f7ce-eb8d-46c0-bdd2-50edb2dfe008)

**Comment by jemaltz** [comment]
Thanks for the reply. I have the attribute in the trigger and it works (in other words, this action is only triggered with the update attribute. A synthetic alert eg for rocket fire does not trigger the update automation).

The issue is that the automation for the update is triggered twice. First, when the synthetic update is sent. And a second time, at the end of the synthetic update's length.

**Comment by amitfin** [comment]
The automation should indeed get triggered twice - once when the update is added to the attribute and once when the update is removed form the attribute. However, the step:
```
condition: "{{ (state_attr('binary_sensor.oref_alert', 'selected_areas_updates') | length) > 0 }}"
```
causes the 2nd time to do nothing.

If you want the automation to not get triggered twice (although it's harmless as the 2nd time it's doing nothing), you can add the same condition to the `conditions` section instead of the `actions` section. It will look the following:
```
alias: Oref Alert Updates
id: oref_alert_updates
triggers:
  - trigger: state
    entity_id: binary_sensor.oref_alert
    attribute: selected_areas_updates
conditions:   
  - condition: "{{ (state_attr('binary_sensor.oref_alert', 'selected_areas_updates') | length) > 0 }}"
actions:
  - variables:
      title: הודעה מפיקוד העורף לאזורך
      message: >-
        {{ state_attr('binary_sensor.oref_alert',
        'selected_areas_updates')[0]['title'] }}
  - action: notify.mobile_app_amits_iphone
    data:
      title: "{{ title }}"
      message: "{{ message }}"
  - action: tts.google_translate_say
    data:
      entity_id: media_player.shelter_speaker
      language: iw
      message: "{{ title }}: {{ message }}"
```

**Comment by jemaltz** [comment]
Okay, got it working. Thanks @amitfin 

This is the way it looks:
```
alias: Pikud HaOref Update
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.oref_alert
    attribute: selected_areas_updates
conditions: []
actions:
  - condition: >-
      {{ (state_attr('binary_sensor.oref_alert', 'selected_areas_updates') |
      length) > 0 }}
[.....]
```

**Comment by amitfin** [comment]
```
alias: Oref Alert Updates
description: ""
triggers:
  - trigger: state
    entity_id: binary_sensor.oref_alert
    attribute: selected_areas_updates
conditions:
  - condition: template
    value_template: >-
      "{{ (state_attr('binary_sensor.oref_alert', 'selected_areas_updates') |
      length) > 0 }}"
actions:
  - variables:
      title: הודעה מפיקוד העורף לאזורך
      message: >-
        {{ state_attr('binary_sensor.oref_alert',
        'selected_areas_updates')[0]['title'] }}
  - action: notify.mobile_app_amits_iphone
    data:
      title: "{{ title }}"
      message: "{{ message }}"
  - action: tts.google_translate_say
    data:
      entity_id: media_player.shelter_speaker
      language: iw
      message: "{{ title }}: {{ message }}"
mode: single
```
