### ISSUE TITLE
טריגר להתראה הראשונית המוקדמת דרך oref_alert_all_areas לא עובד

### ISSUE THREAD

**Issue by razserv2010** [amitfin/oref_alert#231]
### System Health details

Home Assistant OS
Core
2025.6.1
Supervisor
2025.05.5
Operating System
15.2
ממשק
20250531.3

### Checklist

- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of any [previous issues](https://github.com/amitfin/oref_alert/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

אני לא נמצא באזור קבוע כל הזמן ואני רוצה לקבל את ההתראה המוקדמת לפי מיקום שלי אבל דרך oref_alert_all_areas ולא דרך איזור שנקבע מראש.
לפני השינוי הגדול של פיקוד העורף הכל היה עובד כמו שעון ומאז התחילה הבעיה ואותו דבר גם לקבל מצב בטוח  ליציאה מהמיגון
אני מנסה ככה אבל הטריגר לא מתחיל בכלל:

```
alias: פיקוד העורף - מוקדמת (רז)
triggers:
  - trigger: template
    value_template: >-
      {{ state_attr('binary_sensor.oref_alert_all_areas',
      'country_active_alerts')[0]['category'] == 14 }}
  - entity_id: binary_sensor.oref_alert_all_areas
    attribute: country_active_alerts
    trigger: state
    enabled: true
actions:
  - alias: הגדרת משתנים
    variables:
      title: הודעה מפיקוד העורף לאזורך
      previous_length: "{{ trigger.from_state.attributes.country_active_alerts | length }}"
      previous_message: >
        {{ trigger.from_state.attributes.country_active_alerts[0]['title'] if
        previous_length > 0 else None }}
      length: "{{ trigger.to_state.attributes.country_active_alerts | length }}"
      message: >
        {{ trigger.to_state.attributes.country_active_alerts[0]['title'] if
        length > 0 else None }}
      my_area: |
        {{ oref_find_area(
            state_attr('device_tracker.raz_phone', 'latitude'),
            state_attr('device_tracker.raz_phone', 'longitude')
        ) }}
      areas: >
        {{ (trigger.to_state.attributes.country_active_alerts or []) |
        map(attribute='data') | list }}
      alert_text_early: >
        פיקוד העורף זיהה הכנות לשיגור שוקולדים לאזור שאתה נמצא בו:
        {{ my_area }}. בדקות הקרובות צפויות להתקבל התרעות מיידיות , יש להיערך
        בהתאם.
  - alias: תנאי - האם יש הודעה חדשה?
    condition: template
    value_template: "{{ message and message != previous_message }}"
  - alias: תנאי - האם האזור שלי נמצא בהתראות החדשות
    condition: template
    value_template: "{{ my_area in areas }}"
    enabled: true
  - alias: שליחת התראה מוקדמת לטלפון של רז
    action: notify.mobile_app_raz_phone
    data:
      title: התרעה מוקדמת - פיקוד העורף
      message: "{{ alert_text_early }}"
      data:
        ttl: 0
        channel: oref_alert_silance
        priority: high
  - alias: שליחת TTS לפי תנאים
    if:
      - condition: or
        conditions:
          - condition: not
            conditions:
              - condition: state
                entity_id: device_tracker.raz_bermuda_tracker_v1
                state: home
          - condition: state
            entity_id: binary_sensor.door_sensor_kids_room
            state: "on"
    then:
      - alias: שליחת TTS מוקדמת
        action: notify.mobile_app_raz_phone
        data:
          message: TTS
          data:
            ttl: 0
            priority: high
            media_stream: alarm_stream_max
            tts_lang: he
            tts_text: "{{ alert_text_early }}"
        enabled: true
      - action: script.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: script.oref_alert_actions
        enabled: true
mode: single
```

### Reproduction steps

1. כשהגיעה התרעה מוקדמת אז הטריגר לא הופעל

### Debug logs

```text
N/A
```

**Comment by amitfin** [comment]
אני לא חושב שצריך את הטריגר הראשון.
זו אטומציה די מורכבת, ואני לא חושב שזה קשור לבאג באינטגרציה.
תנסה להשתמש במנגנון של דיבוג אוטומציות יחד עם התרעות סינתטיות כדי להבין איפה הבעיה.

**Comment by razserv2010** [comment]
> אני לא חושב שצריך את הטריגר הראשון. זו אטומציה די מורכבת, ואני לא חושב שזה קשור לבאג באינטגרציה. תנסה להשתמש במנגנון של דיבוג אוטומציות יחד עם התרעות סינתטיות כדי להבין איפה הבעיה.

כאשר אני מבצע בדיקה אז entity `binary_sensor.oref_alert_all_areas` לא משתנה 

```
data:
  category: "14"
  area:
    - קריית מוצקין
  duration: 20
  title: בדיקת התראה מוקדמת
action: oref_alert.synthetic_alert
```
